coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "test_*.cpp"
  - "builddir/**/*"
  - "**/*.hpp"  # Header files typically don't need coverage

flags:
  unittests:
    paths:
      - handler.cpp
      - main.cpp
